package dk.jonaslindstrom.math.algebra.concretisations.big;

import java.math.BigInteger;

import dk.jonaslindstrom.math.algebra.concretisations.QuotientRing;

/**
 * This class is an implementation of <i>ℤ / nℤ</i>, eg. the integers <i>ℤ</i> modulo the principal
 * ideal generated by a given integer <i>n</i>.
 * 
 * @author jonas
 *
 */
public class BigIntegersModuloN extends QuotientRing<BigInteger> {

  public BigIntegersModuloN(BigInteger n) {
    super(BigIntegers.getInstance(), n);
  }

  public BigIntegersModuloN(Integer n) {
    this(BigInteger.valueOf(n));
  }
}
