package dk.jonaslindstrom.math.algebra.concretisations;

/**
 * This class is an implementation of <i>ℤ / nℤ</i>, eg. the integers <i>ℤ</i> modulo the principal
 * ideal generated by a given integer <i>n</i>.
 * 
 * @author jonas
 *
 */
public class IntegersModuloN extends QuotientRing<Integer> {

  public IntegersModuloN(Integer n) {
    super(Integers.getInstance(), n);
  }

}
