package dk.jonaslindstrom.ruffini.integers.structures;

import dk.jonaslindstrom.ruffini.common.structures.QuotientRing;

/**
 * This class is an implementation of <i>ℤ / nℤ</i>, e.g. the integers <i>ℤ</i> modulo the principal
 * ideal generated by a given integer <i>n</i>.
 *
 * @author jonas
 */
public class IntegersModuloN extends QuotientRing<Integer> {

    public IntegersModuloN(Integer n) {
        super(Integers.getInstance(), n);
    }

    public int getModulus() {
        return super.mod;
    }

}
